# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.20.0/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.20.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/boygoder/learn/GMP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/boygoder/learn/GMP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.20.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.20.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boygoder/learn/GMP/CMakeFiles /home/boygoder/learn/GMP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boygoder/learn/GMP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_Prufer

# Build rule for target.
test_Prufer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Prufer
.PHONY : test_Prufer

# fast build rule for target.
test_Prufer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Prufer.dir/build.make CMakeFiles/test_Prufer.dir/build
.PHONY : test_Prufer/fast

#=============================================================================
# Target rules for targets named test_Newton

# Build rule for target.
test_Newton: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Newton
.PHONY : test_Newton

# fast build rule for target.
test_Newton/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Newton.dir/build.make CMakeFiles/test_Newton.dir/build
.PHONY : test_Newton/fast

#=============================================================================
# Target rules for targets named PruferTransformer

# Build rule for target.
PruferTransformer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PruferTransformer
.PHONY : PruferTransformer

# fast build rule for target.
PruferTransformer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PruferTransformer.dir/build.make CMakeFiles/PruferTransformer.dir/build
.PHONY : PruferTransformer/fast

#=============================================================================
# Target rules for targets named OrthogonalPolynomials

# Build rule for target.
OrthogonalPolynomials: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OrthogonalPolynomials
.PHONY : OrthogonalPolynomials

# fast build rule for target.
OrthogonalPolynomials/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrthogonalPolynomials.dir/build.make CMakeFiles/OrthogonalPolynomials.dir/build
.PHONY : OrthogonalPolynomials/fast

#=============================================================================
# Target rules for targets named test_Gauss

# Build rule for target.
test_Gauss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Gauss
.PHONY : test_Gauss

# fast build rule for target.
test_Gauss/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Gauss.dir/build.make CMakeFiles/test_Gauss.dir/build
.PHONY : test_Gauss/fast

#=============================================================================
# Target rules for targets named test_RungeKutta

# Build rule for target.
test_RungeKutta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_RungeKutta
.PHONY : test_RungeKutta

# fast build rule for target.
test_RungeKutta/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_RungeKutta.dir/build.make CMakeFiles/test_RungeKutta.dir/build
.PHONY : test_RungeKutta/fast

#=============================================================================
# Target rules for targets named polynomial

# Build rule for target.
polynomial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 polynomial
.PHONY : polynomial

# fast build rule for target.
polynomial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polynomial.dir/build.make CMakeFiles/polynomial.dir/build
.PHONY : polynomial/fast

#=============================================================================
# Target rules for targets named gmptools

# Build rule for target.
gmptools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmptools
.PHONY : gmptools

# fast build rule for target.
gmptools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmptools.dir/build.make CMakeFiles/gmptools.dir/build
.PHONY : gmptools/fast

#=============================================================================
# Target rules for targets named RungeKutta

# Build rule for target.
RungeKutta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RungeKutta
.PHONY : RungeKutta

# fast build rule for target.
RungeKutta/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RungeKutta.dir/build.make CMakeFiles/RungeKutta.dir/build
.PHONY : RungeKutta/fast

#=============================================================================
# Target rules for targets named NewtonMethod

# Build rule for target.
NewtonMethod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewtonMethod
.PHONY : NewtonMethod

# fast build rule for target.
NewtonMethod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonMethod.dir/build.make CMakeFiles/NewtonMethod.dir/build
.PHONY : NewtonMethod/fast

#=============================================================================
# Target rules for targets named test_OrthoPoly

# Build rule for target.
test_OrthoPoly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_OrthoPoly
.PHONY : test_OrthoPoly

# fast build rule for target.
test_OrthoPoly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_OrthoPoly.dir/build.make CMakeFiles/test_OrthoPoly.dir/build
.PHONY : test_OrthoPoly/fast

#=============================================================================
# Target rules for targets named GaussIntegralTableGenerator

# Build rule for target.
GaussIntegralTableGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GaussIntegralTableGenerator
.PHONY : GaussIntegralTableGenerator

# fast build rule for target.
GaussIntegralTableGenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussIntegralTableGenerator.dir/build.make CMakeFiles/GaussIntegralTableGenerator.dir/build
.PHONY : GaussIntegralTableGenerator/fast

#=============================================================================
# Target rules for targets named test_gmp

# Build rule for target.
test_gmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gmp
.PHONY : test_gmp

# fast build rule for target.
test_gmp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gmp.dir/build.make CMakeFiles/test_gmp.dir/build
.PHONY : test_gmp/fast

#=============================================================================
# Target rules for targets named GaussianPoint

# Build rule for target.
GaussianPoint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GaussianPoint
.PHONY : GaussianPoint

# fast build rule for target.
GaussianPoint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussianPoint.dir/build.make CMakeFiles/GaussianPoint.dir/build
.PHONY : GaussianPoint/fast

#=============================================================================
# Target rules for targets named test_polynomial

# Build rule for target.
test_polynomial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_polynomial
.PHONY : test_polynomial

# fast build rule for target.
test_polynomial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/build
.PHONY : test_polynomial/fast

GaussIntegralTableGenerator.o: GaussIntegralTableGenerator.cpp.o
.PHONY : GaussIntegralTableGenerator.o

# target to build an object file
GaussIntegralTableGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussIntegralTableGenerator.dir/build.make CMakeFiles/GaussIntegralTableGenerator.dir/GaussIntegralTableGenerator.cpp.o
.PHONY : GaussIntegralTableGenerator.cpp.o

GaussIntegralTableGenerator.i: GaussIntegralTableGenerator.cpp.i
.PHONY : GaussIntegralTableGenerator.i

# target to preprocess a source file
GaussIntegralTableGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussIntegralTableGenerator.dir/build.make CMakeFiles/GaussIntegralTableGenerator.dir/GaussIntegralTableGenerator.cpp.i
.PHONY : GaussIntegralTableGenerator.cpp.i

GaussIntegralTableGenerator.s: GaussIntegralTableGenerator.cpp.s
.PHONY : GaussIntegralTableGenerator.s

# target to generate assembly for a file
GaussIntegralTableGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussIntegralTableGenerator.dir/build.make CMakeFiles/GaussIntegralTableGenerator.dir/GaussIntegralTableGenerator.cpp.s
.PHONY : GaussIntegralTableGenerator.cpp.s

GaussianPoint.o: GaussianPoint.cpp.o
.PHONY : GaussianPoint.o

# target to build an object file
GaussianPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussianPoint.dir/build.make CMakeFiles/GaussianPoint.dir/GaussianPoint.cpp.o
.PHONY : GaussianPoint.cpp.o

GaussianPoint.i: GaussianPoint.cpp.i
.PHONY : GaussianPoint.i

# target to preprocess a source file
GaussianPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussianPoint.dir/build.make CMakeFiles/GaussianPoint.dir/GaussianPoint.cpp.i
.PHONY : GaussianPoint.cpp.i

GaussianPoint.s: GaussianPoint.cpp.s
.PHONY : GaussianPoint.s

# target to generate assembly for a file
GaussianPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GaussianPoint.dir/build.make CMakeFiles/GaussianPoint.dir/GaussianPoint.cpp.s
.PHONY : GaussianPoint.cpp.s

NewtonMethod.o: NewtonMethod.cpp.o
.PHONY : NewtonMethod.o

# target to build an object file
NewtonMethod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonMethod.dir/build.make CMakeFiles/NewtonMethod.dir/NewtonMethod.cpp.o
.PHONY : NewtonMethod.cpp.o

NewtonMethod.i: NewtonMethod.cpp.i
.PHONY : NewtonMethod.i

# target to preprocess a source file
NewtonMethod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonMethod.dir/build.make CMakeFiles/NewtonMethod.dir/NewtonMethod.cpp.i
.PHONY : NewtonMethod.cpp.i

NewtonMethod.s: NewtonMethod.cpp.s
.PHONY : NewtonMethod.s

# target to generate assembly for a file
NewtonMethod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewtonMethod.dir/build.make CMakeFiles/NewtonMethod.dir/NewtonMethod.cpp.s
.PHONY : NewtonMethod.cpp.s

OrthogonalPolynomials.o: OrthogonalPolynomials.cpp.o
.PHONY : OrthogonalPolynomials.o

# target to build an object file
OrthogonalPolynomials.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrthogonalPolynomials.dir/build.make CMakeFiles/OrthogonalPolynomials.dir/OrthogonalPolynomials.cpp.o
.PHONY : OrthogonalPolynomials.cpp.o

OrthogonalPolynomials.i: OrthogonalPolynomials.cpp.i
.PHONY : OrthogonalPolynomials.i

# target to preprocess a source file
OrthogonalPolynomials.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrthogonalPolynomials.dir/build.make CMakeFiles/OrthogonalPolynomials.dir/OrthogonalPolynomials.cpp.i
.PHONY : OrthogonalPolynomials.cpp.i

OrthogonalPolynomials.s: OrthogonalPolynomials.cpp.s
.PHONY : OrthogonalPolynomials.s

# target to generate assembly for a file
OrthogonalPolynomials.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrthogonalPolynomials.dir/build.make CMakeFiles/OrthogonalPolynomials.dir/OrthogonalPolynomials.cpp.s
.PHONY : OrthogonalPolynomials.cpp.s

PruferTransformer.o: PruferTransformer.cpp.o
.PHONY : PruferTransformer.o

# target to build an object file
PruferTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PruferTransformer.dir/build.make CMakeFiles/PruferTransformer.dir/PruferTransformer.cpp.o
.PHONY : PruferTransformer.cpp.o

PruferTransformer.i: PruferTransformer.cpp.i
.PHONY : PruferTransformer.i

# target to preprocess a source file
PruferTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PruferTransformer.dir/build.make CMakeFiles/PruferTransformer.dir/PruferTransformer.cpp.i
.PHONY : PruferTransformer.cpp.i

PruferTransformer.s: PruferTransformer.cpp.s
.PHONY : PruferTransformer.s

# target to generate assembly for a file
PruferTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PruferTransformer.dir/build.make CMakeFiles/PruferTransformer.dir/PruferTransformer.cpp.s
.PHONY : PruferTransformer.cpp.s

RungeKutta.o: RungeKutta.cpp.o
.PHONY : RungeKutta.o

# target to build an object file
RungeKutta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RungeKutta.dir/build.make CMakeFiles/RungeKutta.dir/RungeKutta.cpp.o
.PHONY : RungeKutta.cpp.o

RungeKutta.i: RungeKutta.cpp.i
.PHONY : RungeKutta.i

# target to preprocess a source file
RungeKutta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RungeKutta.dir/build.make CMakeFiles/RungeKutta.dir/RungeKutta.cpp.i
.PHONY : RungeKutta.cpp.i

RungeKutta.s: RungeKutta.cpp.s
.PHONY : RungeKutta.s

# target to generate assembly for a file
RungeKutta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RungeKutta.dir/build.make CMakeFiles/RungeKutta.dir/RungeKutta.cpp.s
.PHONY : RungeKutta.cpp.s

gmptools.o: gmptools.cpp.o
.PHONY : gmptools.o

# target to build an object file
gmptools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmptools.dir/build.make CMakeFiles/gmptools.dir/gmptools.cpp.o
.PHONY : gmptools.cpp.o

gmptools.i: gmptools.cpp.i
.PHONY : gmptools.i

# target to preprocess a source file
gmptools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmptools.dir/build.make CMakeFiles/gmptools.dir/gmptools.cpp.i
.PHONY : gmptools.cpp.i

gmptools.s: gmptools.cpp.s
.PHONY : gmptools.s

# target to generate assembly for a file
gmptools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmptools.dir/build.make CMakeFiles/gmptools.dir/gmptools.cpp.s
.PHONY : gmptools.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

polynomial.o: polynomial.cpp.o
.PHONY : polynomial.o

# target to build an object file
polynomial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polynomial.dir/build.make CMakeFiles/polynomial.dir/polynomial.cpp.o
.PHONY : polynomial.cpp.o

polynomial.i: polynomial.cpp.i
.PHONY : polynomial.i

# target to preprocess a source file
polynomial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polynomial.dir/build.make CMakeFiles/polynomial.dir/polynomial.cpp.i
.PHONY : polynomial.cpp.i

polynomial.s: polynomial.cpp.s
.PHONY : polynomial.s

# target to generate assembly for a file
polynomial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polynomial.dir/build.make CMakeFiles/polynomial.dir/polynomial.cpp.s
.PHONY : polynomial.cpp.s

test_Gauss.o: test_Gauss.cpp.o
.PHONY : test_Gauss.o

# target to build an object file
test_Gauss.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Gauss.dir/build.make CMakeFiles/test_Gauss.dir/test_Gauss.cpp.o
.PHONY : test_Gauss.cpp.o

test_Gauss.i: test_Gauss.cpp.i
.PHONY : test_Gauss.i

# target to preprocess a source file
test_Gauss.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Gauss.dir/build.make CMakeFiles/test_Gauss.dir/test_Gauss.cpp.i
.PHONY : test_Gauss.cpp.i

test_Gauss.s: test_Gauss.cpp.s
.PHONY : test_Gauss.s

# target to generate assembly for a file
test_Gauss.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Gauss.dir/build.make CMakeFiles/test_Gauss.dir/test_Gauss.cpp.s
.PHONY : test_Gauss.cpp.s

test_Newton.o: test_Newton.cpp.o
.PHONY : test_Newton.o

# target to build an object file
test_Newton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Newton.dir/build.make CMakeFiles/test_Newton.dir/test_Newton.cpp.o
.PHONY : test_Newton.cpp.o

test_Newton.i: test_Newton.cpp.i
.PHONY : test_Newton.i

# target to preprocess a source file
test_Newton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Newton.dir/build.make CMakeFiles/test_Newton.dir/test_Newton.cpp.i
.PHONY : test_Newton.cpp.i

test_Newton.s: test_Newton.cpp.s
.PHONY : test_Newton.s

# target to generate assembly for a file
test_Newton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Newton.dir/build.make CMakeFiles/test_Newton.dir/test_Newton.cpp.s
.PHONY : test_Newton.cpp.s

test_OrthoPoly.o: test_OrthoPoly.cpp.o
.PHONY : test_OrthoPoly.o

# target to build an object file
test_OrthoPoly.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_OrthoPoly.dir/build.make CMakeFiles/test_OrthoPoly.dir/test_OrthoPoly.cpp.o
.PHONY : test_OrthoPoly.cpp.o

test_OrthoPoly.i: test_OrthoPoly.cpp.i
.PHONY : test_OrthoPoly.i

# target to preprocess a source file
test_OrthoPoly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_OrthoPoly.dir/build.make CMakeFiles/test_OrthoPoly.dir/test_OrthoPoly.cpp.i
.PHONY : test_OrthoPoly.cpp.i

test_OrthoPoly.s: test_OrthoPoly.cpp.s
.PHONY : test_OrthoPoly.s

# target to generate assembly for a file
test_OrthoPoly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_OrthoPoly.dir/build.make CMakeFiles/test_OrthoPoly.dir/test_OrthoPoly.cpp.s
.PHONY : test_OrthoPoly.cpp.s

test_Prufer.o: test_Prufer.cpp.o
.PHONY : test_Prufer.o

# target to build an object file
test_Prufer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Prufer.dir/build.make CMakeFiles/test_Prufer.dir/test_Prufer.cpp.o
.PHONY : test_Prufer.cpp.o

test_Prufer.i: test_Prufer.cpp.i
.PHONY : test_Prufer.i

# target to preprocess a source file
test_Prufer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Prufer.dir/build.make CMakeFiles/test_Prufer.dir/test_Prufer.cpp.i
.PHONY : test_Prufer.cpp.i

test_Prufer.s: test_Prufer.cpp.s
.PHONY : test_Prufer.s

# target to generate assembly for a file
test_Prufer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Prufer.dir/build.make CMakeFiles/test_Prufer.dir/test_Prufer.cpp.s
.PHONY : test_Prufer.cpp.s

test_RungeKutta.o: test_RungeKutta.cpp.o
.PHONY : test_RungeKutta.o

# target to build an object file
test_RungeKutta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_RungeKutta.dir/build.make CMakeFiles/test_RungeKutta.dir/test_RungeKutta.cpp.o
.PHONY : test_RungeKutta.cpp.o

test_RungeKutta.i: test_RungeKutta.cpp.i
.PHONY : test_RungeKutta.i

# target to preprocess a source file
test_RungeKutta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_RungeKutta.dir/build.make CMakeFiles/test_RungeKutta.dir/test_RungeKutta.cpp.i
.PHONY : test_RungeKutta.cpp.i

test_RungeKutta.s: test_RungeKutta.cpp.s
.PHONY : test_RungeKutta.s

# target to generate assembly for a file
test_RungeKutta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_RungeKutta.dir/build.make CMakeFiles/test_RungeKutta.dir/test_RungeKutta.cpp.s
.PHONY : test_RungeKutta.cpp.s

test_gmp.o: test_gmp.cpp.o
.PHONY : test_gmp.o

# target to build an object file
test_gmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gmp.dir/build.make CMakeFiles/test_gmp.dir/test_gmp.cpp.o
.PHONY : test_gmp.cpp.o

test_gmp.i: test_gmp.cpp.i
.PHONY : test_gmp.i

# target to preprocess a source file
test_gmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gmp.dir/build.make CMakeFiles/test_gmp.dir/test_gmp.cpp.i
.PHONY : test_gmp.cpp.i

test_gmp.s: test_gmp.cpp.s
.PHONY : test_gmp.s

# target to generate assembly for a file
test_gmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gmp.dir/build.make CMakeFiles/test_gmp.dir/test_gmp.cpp.s
.PHONY : test_gmp.cpp.s

test_polynomial.o: test_polynomial.cpp.o
.PHONY : test_polynomial.o

# target to build an object file
test_polynomial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.o
.PHONY : test_polynomial.cpp.o

test_polynomial.i: test_polynomial.cpp.i
.PHONY : test_polynomial.i

# target to preprocess a source file
test_polynomial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.i
.PHONY : test_polynomial.cpp.i

test_polynomial.s: test_polynomial.cpp.s
.PHONY : test_polynomial.s

# target to generate assembly for a file
test_polynomial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.s
.PHONY : test_polynomial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GaussIntegralTableGenerator"
	@echo "... GaussianPoint"
	@echo "... NewtonMethod"
	@echo "... OrthogonalPolynomials"
	@echo "... PruferTransformer"
	@echo "... RungeKutta"
	@echo "... gmptools"
	@echo "... main"
	@echo "... polynomial"
	@echo "... test_Gauss"
	@echo "... test_Newton"
	@echo "... test_OrthoPoly"
	@echo "... test_Prufer"
	@echo "... test_RungeKutta"
	@echo "... test_gmp"
	@echo "... test_polynomial"
	@echo "... GaussIntegralTableGenerator.o"
	@echo "... GaussIntegralTableGenerator.i"
	@echo "... GaussIntegralTableGenerator.s"
	@echo "... GaussianPoint.o"
	@echo "... GaussianPoint.i"
	@echo "... GaussianPoint.s"
	@echo "... NewtonMethod.o"
	@echo "... NewtonMethod.i"
	@echo "... NewtonMethod.s"
	@echo "... OrthogonalPolynomials.o"
	@echo "... OrthogonalPolynomials.i"
	@echo "... OrthogonalPolynomials.s"
	@echo "... PruferTransformer.o"
	@echo "... PruferTransformer.i"
	@echo "... PruferTransformer.s"
	@echo "... RungeKutta.o"
	@echo "... RungeKutta.i"
	@echo "... RungeKutta.s"
	@echo "... gmptools.o"
	@echo "... gmptools.i"
	@echo "... gmptools.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... polynomial.o"
	@echo "... polynomial.i"
	@echo "... polynomial.s"
	@echo "... test_Gauss.o"
	@echo "... test_Gauss.i"
	@echo "... test_Gauss.s"
	@echo "... test_Newton.o"
	@echo "... test_Newton.i"
	@echo "... test_Newton.s"
	@echo "... test_OrthoPoly.o"
	@echo "... test_OrthoPoly.i"
	@echo "... test_OrthoPoly.s"
	@echo "... test_Prufer.o"
	@echo "... test_Prufer.i"
	@echo "... test_Prufer.s"
	@echo "... test_RungeKutta.o"
	@echo "... test_RungeKutta.i"
	@echo "... test_RungeKutta.s"
	@echo "... test_gmp.o"
	@echo "... test_gmp.i"
	@echo "... test_gmp.s"
	@echo "... test_polynomial.o"
	@echo "... test_polynomial.i"
	@echo "... test_polynomial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

